### PR TITLE
Upload ARPA json file

### PR DESCRIPTION
**Pull request by codykallen**
This PR adds the American Rescue Plan Act of 2021 to the examples repo. For a description of the relevant policy provisions, see [Tax-Calculator issue #2571](https://github.com/PSLmodels/Tax-Calculator/issues/2571).

@MattHJensen

### CODE REVIEW

**Comment by codykallen** [comment]
Note that using this file will require the new policy parameters in [Tax-Calculator PR #2573](https://github.com/PSLmodels/Tax-Calculator/pull/2573).

**Comment by jdebacker** [comment]
Excellent - thanks for this addition @codykallen.  I'll merge this in when Tax-Calculator PR #2573 is complete and merged.

**Comment by codykallen** [comment]
ARPA raises the EITC's investment income cutoff to $10,000 (indexed to inflation). This change is permanent. The recent commit makes this change permanent instead of temporary.

**Comment by jdebacker** [comment]
@codykallen I just opened a PR to your branch to make the updates necessary for the tests to pass here.  

If you merge that, give me the thumbs up that your reform file is ready and I will merge it into the repo.

**Comment by jdebacker** [comment]
@codykallen thanks for this.  I'm merging here and will fix remaining error in separate PR.

**Pull request merged**
