### PR TITLE
Biden 2020 campaign proposals

### PR DESCRIPTION
**Pull request by jdebacker**
This PR adds the Biden 2020 campaign proposals to the catalog of reform examples.

### CODE REVIEW

**Comment by jdebacker** [comment]
@Peter-Metz @MattHJensen I think this is good to go.  Would you mind giving it a look?

**Comment by Peter-Metz** [comment]
Hi Jason, just a few comments here based on my and Kyle's work on the [Tax-Cruncher-Biden](https://compute.studio/AEIEconomics/Tax-Cruncher-Biden/) app:
- We instituted the Pease limitation (`ID_ps`) starting at $400,000 for all filers.
- You could include the removal of the SALT deduction cap by setting `ID_AllTaxes_c` to 9e99
- For the tax brackets, it looks like you're missing the 35% bracket. Here's how we approached the (confusing) parametrization. Same goes for the pass-through brackets:

```
      "II_brk5": {"2021": [400000.0, 400000.0, 200000.0, 400000.0, 400000.0],
                  "2026": [482682.0, 482682.0, 241341.0, 482682.0, 482682.0]},
      "II_rt6": {"2021": 0.33, "2026": 0.35},
      "II_brk6": {"2021": [416700.0, 416700.0, 208350.0, 416700.0, 416700.0],
                  "2026": [484651.0, 545233.0, 272616.0, 514942.0, 545233.0]},
      "II_rt7": {"2021": 0.35, "2026": 0.396},
      "II_brk7": {"2021": [418400.0, 470700.0, 235350.0, 444550.0, 470700.0],
                  "2026": [9e99, 9e99, 9e99, 9e99, 9e99]},
      "II_rt8": {"2021":0.396, "2026": 1.0}

**Comment by jdebacker** [comment]
@Peter-Metz Thanks for the comments!

> We instituted the Pease limitation (ID_ps) starting at $400,000 for all filers.

One clarification: did you assume the $400,000 threshold for the Pease limitation just for 2021-2026, then revert to current law thresholds after that time?  Or did you apply the $400,000 threshold in all years, 2021 and beyond?

**Comment by jdebacker** [comment]
One more @Peter-Metz:

> You could include the removal of the SALT deduction cap by setting ID_AllTaxes_c to 9e99

Is this something that you all did or think is a good assumption given details of the proposal?  [TPC assumes](https://www.taxpolicycenter.org/sites/default/files/publication/160472/an_updated_analysis_of_former_vice_president_bidens_tax_proposals_11-6-20_correction_1.pdf) (see footnote 13) that the Biden proposals do not change current law on limitations on the state and local tax deductions (i.e., limitations apply until 2026).

**Comment by Peter-Metz** [comment]
>One clarification: did you assume the $400,000 threshold for the Pease limitation just for 2021-2026, then revert to current law thresholds after that time?

Yup, we reverted the threshold in 2026. Here was our adjustment:

```
      "ID_ps": {"2021": [400000.0,400000.0,200000.0,400000.0,400000.0],
                "2026": [302907.0, 363489.0, 181744.0, 333198.0, 363489.0]}
```

Re: SALT deduction:

>Is this something that you all did or think is a good assumption given details of the proposal?

This is something we did -- we were following [Pomerleau](https://www.aei.org/research-products/report/an-analysis-of-joe-bidens-tax-proposals-october-2020-update/) and [Rubin](https://www.wsj.com/articles/how-bidens-tax-plan-might-affect-five-american-households-11599739200). It's interesting that TPC assumes the opposite. I'm not entirely sure of the basis for either assumption.

**Comment by jdebacker** [comment]
@Peter-Metz Thanks again!  I've updated the threshold for the Pease limitation.

**Pull request merged**
